### ISSUE TITLE
pitch in stadium renders sport twice

### ISSUE THREAD

**Issue by HolgerJeromin** [giggls/openstreetmap-carto-de#10]
https://www.openstreetmap.de/karte.html?zoom=18&lat=51.88335&lon=8.51342&layers=B000TT

The leisure=stadium and leisure=pitch have sport=soccer so both are rendered 8-/

see http://trac.openstreetmap.fr/ticket/536

**Comment by giggls** [comment]
This is likely the case on very small stadiums (roughly the size of the pitch itself) only. I have no Idea how to fix this rather than using complicated spatial queries checking for pitches inside stadiums before rendering anything. However, the query is already somewhat complicated :( (see project.yaml line 648). Feel free to send pull-requests though :)

**Comment by HolgerJeromin** [comment]
I see no reason to render lines in stadium at all. 
Outdoor stadium should get pitches, stadium with a roof would look strange with lines on the roof

**Comment by giggls** [comment]
Thus you think I should expand my SQL where clause by something like "where leisure='pitch'" or (less intrusive) "where leisure != 'stadium'"? Currently anything with a sport tag and no building tag is taken.

**Comment by HolgerJeromin** [comment]
Thanks :-)
