### ISSUE TITLE
Tennis lines and color are rendered too late

### ISSUE THREAD

**Issue by HolgerJeromin** [giggls/openstreetmap-carto-de#13]
https://www.openstreetmap.de/karte.html?zoom=15&lat=51.87851&lon=8.49822&layers=B000TT
Tennis on the west has no clay color and lines at zoom 15. But soccer has lines and grass color.

**Comment by giggls** [comment]
AFAIR this code has been taken more or less unchanged from https://github.com/cquest/osmfr-cartocss/blob/master/golf.mss "too late" is in the eye of the beholder :) I suppose Christian Quest did this because tennis courts are usually smaller than soccer fields. If changing something **at all** I would tend to not render soccer fields this early. Have a look at https://github.com/giggls/openstreetmap-carto-de/blob/master/sport.mss

**Comment by HolgerJeromin** [comment]
The change of the color is confusing.
