### ISSUE TITLE
Modifications in project.yaml

### ISSUE THREAD

**Issue by Quintus** [giggls/openstreetmap-carto-de#47]
INSTALL-de.md says:

> If l10n is not needed it is also possible to slightly modify either project.yaml or the database views provided in the views_osmde directory.

What kind of modifications are required? I'm only rendering maps for places in Germany, so I assume I don't need the l10n extension (whose dependencies I'd like to avoid -- I don't want to install an entire llvm toolchain just for this).

**Comment by giggls** [comment]
Really? Are these modifications that complicated, that they need explanation?
I did not think so that's why I don't have a detailed manual.

In  project.mml you need to replace all occurances of localized_name_second, localized_name_first, localized_name_without_brackets and localized_streetname by name only.

Changing the views instead you would add something like this instead of the osml10n function calls:

```
name as localized_name_second,
name as localized_name_first,
name as localized_name_without_brackets,
name as  localized_streetname
```
This will also disable the code for generating streetname abbreviations because this is also part of osml10n.

**Comment by Quintus** [comment]
> Really? Are these modifications that complicated, that they need explanation?

I did not intend to offend you. I asked a genuine question, and you reply with a personal attack. I don't think you're doing yourself a favour with this attitude, but I take your point. I don't work with OSM data on a daily base like you do, and I don't even touch much SQL at all.

Thank you for the advice, though. I'll try it, and if it works out, it's okay. If not, I'll just go with the official OSM style.

**Comment by giggls** [comment]
OK, you consider my reply an offence. I don't. So don't expect any further help from me then.
