### ISSUE TITLE
SQL error in water-lines layer

### ISSUE THREAD

**Issue by alexandervlpl** [giggls/openstreetmap-carto-de#62]
There seems to be a problem rendering `water-lines`:
```
RuntimeError: Postgis Plugin: ERROR:  COALESCE types text and integer cannot be matched
LINE 13:   ORDER BY COALESCE(layer,0)
...
encountered during parsing of layer 'water-lines' in Layer
```

**Comment by giggls** [comment]
I am getting kind of angry with those kind of (non) issues now.

Please follow the official path! If you don't (using contrib) you are on your own. 

This version of the code is in productive use and does not have such issues if you follow the documented path.

**Comment by alexandervlpl** [comment]
Sorry about that. Perhaps you can add a warning about contrib (and the "standard" OSM database), as well as something about the future of the project in the README and INSTALL-de.md? I got the impression that this was all fully supported, there is no indication otherwise.

**Comment by giggls** [comment]
No, you did **not** follow the documented path as you are using upstream database layout which was never officially supported and might well be incompatible because this project is not actively maintained for about 2 years now.

Please use the hstore-only approach which is currently still running on https://tile.openstreetmap.de

See this blog post for the reasons:
 https://blog.geggus.net/2020/09/why-development-of-german-osm-carto-style-is-currently-stuck/

The osm2pgsql issue I describe there has now been resolved and my new approach for l10n can be implemented now.

So in any case if you try to deploy this code now it is going to get deprecated as soon as my new approach will work.
